### ISSUE TITLE
Make `ControlPlaneRef` an optional pointer for non konnect-native objects

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-configuration#31]
## Current Behavior

Some objects that are not konnect-native (such as consumers, that are used in the context ok KIC as well), could have the `ControlPlaneRef` field migrated to an optional, `omitempty` pointer.

This way we can get rid of the default `controlPlaneRef` set to KIC. This issue is a proposal still to be discussed.

**Comment by pmalek** [comment]
Reopening as not all entities have `ControlPlaneRef` set as optional yet.

**Comment by pmalek** [comment]
Searching through the project it seems that we already use a pointer to `ControlPlaneRef` in every object that does have a control plane ref. 

Closing.

---

#119 adds `kic` `ControlPlaneRef` type to allow explicitly stating the cp ref type (apart from the agreed implicit default, meaning that an object is to be reconciled by KIC). cc @mlavacca
